/* ============================================================
   PAISLEY PIE CO. — SITE CONTENT (generated by admin.html)
   Replace this file in your website folder to publish changes.
   ============================================================ */
window.PPC_DATA = {
  "info": {
    "name": "Paisley Pie Co.",
    "addressLine": "25 Causeyside St, Paisley PA1 1UL",
    "addressShort": "25 Causeyside Street",
    "phone": "0141 889 8480",
    "phoneHref": "01418898480",
    "instagram": "@paisleypieco",
    "instagramUrl": "https://www.instagram.com/paisleypieco/",
    "priceRange": "£10–20 per person",
    "mapQuery": "25 Causeyside St, Paisley PA1 1UL",
    "deliveryFee": 2.5,
    "hours": [
      {
        "day": "Monday",
        "time": "10:00 am – 4:00 pm"
      },
      {
        "day": "Tuesday",
        "time": "10:00 am – 4:00 pm"
      },
      {
        "day": "Wednesday",
        "time": "10:00 am – 4:00 pm"
      },
      {
        "day": "Thursday",
        "time": "10:00 am – 4:00 pm"
      },
      {
        "day": "Friday",
        "time": "10:00 am – 4:00 pm"
      },
      {
        "day": "Saturday",
        "time": "10:00 am – 4:00 pm"
      },
      {
        "day": "Sunday",
        "time": "Closed"
      }
    ]
  },
  "siteStatus": {
    "ordersOpen": true,
    "busyTitle": "WE'RE SLAMMED RIGHT NOW",
    "busyMessage": "Our kitchen is at full capacity, so online ordering is paused for a wee bit. We'll be back ASAP — pop your email in below and we'll let you know the moment we're taking orders again."
  },
  "menuCategories": [
    {
      "key": "signature",
      "title": "Signature & Viral",
      "note": "The ones that put us on the map"
    },
    {
      "key": "fusion",
      "title": "Fusion Pies",
      "note": "If it tastes amazing, it can go in a pie"
    },
    {
      "key": "classic",
      "title": "Classic Pies",
      "note": "The Scottish staples, done right"
    },
    {
      "key": "snacks",
      "title": "Hot Snacks & Rolls",
      "note": "Hot, handheld, ready in seconds"
    },
    {
      "key": "sweet",
      "title": "Sweet Bakes",
      "note": "Baked fresh every morning"
    },
    {
      "key": "drinks",
      "title": "Drinks",
      "note": "Wash it down"
    }
  ],
  "menu": [
    {
      "id": "donner",
      "cat": "signature",
      "name": "The Big Daddy Donner",
      "price": 4.8,
      "desc": "Generous donner meat in a rich spiced house sauce, sealed in golden puff pastry. 5 million views and counting.",
      "badge": "hot",
      "badgeText": "🔥 Viral",
      "home": true,
      "homeTag": "🔥 Viral Hit",
      "homeTagDark": false,
      "img": "https://itin-dev.wanderlogstatic.com/freeImage/XJqb3QVHLFX3z3TPQVuhhCsqKTcNPnsb"
    },
    {
      "id": "steak-bp",
      "cat": "signature",
      "name": "Steak & Stornoway Black Pudding",
      "price": 4.8,
      "desc": "Succulent Scottish beef with black pudding from Charles Macleod, in a dark rich gravy.",
      "badge": "",
      "badgeText": "",
      "home": true,
      "homeTag": "Classic",
      "homeTagDark": true,
      "img": "https://images.unsplash.com/photo-1518311297794-ec7298ffba64?auto=format&fit=crop&w=700&q=80"
    },
    {
      "id": "steak-haggis",
      "cat": "signature",
      "name": "Steak & Haggis",
      "price": 4.8,
      "desc": "Huge pieces of beef and proper haggis under that signature buttery lid.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "balmoral",
      "cat": "signature",
      "name": "Chicken Balmoral",
      "price": 6.7,
      "desc": "Chicken, haggis and a creamy whisky-pepper sauce. A Scottish classic, pie-d.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "south-indian",
      "cat": "fusion",
      "name": "South Indian Chicken",
      "price": 4.5,
      "desc": "Tender chicken in a warmly spiced South Indian curry sauce.",
      "badge": "",
      "badgeText": "Fan Fave",
      "home": true,
      "homeTag": "Fan Favourite",
      "homeTagDark": true,
      "img": "https://images.unsplash.com/photo-1581986675622-41eccf27129d?auto=format&fit=crop&w=700&q=80"
    },
    {
      "id": "chasni",
      "cat": "fusion",
      "name": "Chicken Tikka Chasni",
      "price": 4.5,
      "desc": "Chicken tikka in a sweet, tangy chasni sauce. A west-coast fusion favourite.",
      "badge": "",
      "badgeText": "",
      "home": true,
      "homeTag": "Fan Favourite",
      "homeTagDark": true,
      "img": "https://images.unsplash.com/photo-1534432182912-63863115e106?auto=format&fit=crop&w=700&q=80"
    },
    {
      "id": "katsu",
      "cat": "fusion",
      "name": "Katsu Chicken Curry",
      "price": 4.5,
      "desc": "Crispy-style chicken in a mild Japanese katsu sauce.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "butter",
      "cat": "fusion",
      "name": "Butter Chicken",
      "price": 4.5,
      "desc": "Rich, creamy butter chicken sealed under golden pastry.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "halloumi",
      "cat": "fusion",
      "name": "Sweet Chilli Halloumi",
      "price": 4.5,
      "desc": "Grilled halloumi and peppers in a sticky sweet chilli glaze.",
      "badge": "v",
      "badgeText": "Veg",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "scotch",
      "cat": "classic",
      "name": "Scotch Pie",
      "price": 2.2,
      "desc": "The original. Seasoned minced mutton in a hot-water crust shell.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "steak",
      "cat": "classic",
      "name": "Steak Pie",
      "price": 4.5,
      "desc": "Slow-cooked Scottish steak in hearty gravy.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "mince",
      "cat": "classic",
      "name": "Mince & Tatties Pie",
      "price": 4.2,
      "desc": "Proper mince and mashed potato. Comfort in a crust.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "mac",
      "cat": "classic",
      "name": "Macaroni Cheese Pie",
      "price": 3.9,
      "desc": "Creamy mac & cheese packed into a crispy shortcrust shell.",
      "badge": "v",
      "badgeText": "Veg",
      "home": true,
      "homeTag": "Scottish Classic",
      "homeTagDark": true,
      "img": "https://images.unsplash.com/photo-1608039783021-6116a558f0c5?auto=format&fit=crop&w=700&q=80"
    },
    {
      "id": "chicken-mush",
      "cat": "classic",
      "name": "Chicken & Mushroom",
      "price": 4.2,
      "desc": "Chicken in a creamy mushroom sauce. Always a seller.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "sausage",
      "cat": "snacks",
      "name": "Sausage Roll",
      "price": 2.2,
      "desc": "Flaky puff pastry, proper sausage meat. Best seller off the hot counter.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "bp-roll",
      "cat": "snacks",
      "name": "Black Pudding Roll",
      "price": 2.5,
      "desc": "Stornoway black pudding wrapped in pastry.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "cheese-onion",
      "cat": "snacks",
      "name": "Cheese & Onion Roll",
      "price": 2.3,
      "desc": "Mature cheddar and onion in golden pastry.",
      "badge": "v",
      "badgeText": "Veg",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "bridie",
      "cat": "snacks",
      "name": "Steak Bridie",
      "price": 3.2,
      "desc": "Forfar-style folded pastry filled with seasoned steak.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "empire",
      "cat": "sweet",
      "name": "Empire Biscuit",
      "price": 2.5,
      "desc": "Our empire biscuit has a surprising coconut hit that keeps folk coming back.",
      "badge": "",
      "badgeText": "Cult Fave",
      "home": true,
      "homeTag": "Sweet",
      "homeTagDark": true,
      "img": "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?auto=format&fit=crop&w=700&q=80"
    },
    {
      "id": "tiffin",
      "cat": "sweet",
      "name": "Tiffin",
      "price": 2.2,
      "desc": "Chocolate fridge cake with a biscuit crunch.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "cake",
      "cat": "sweet",
      "name": "Daily Cake (slice)",
      "price": 3.2,
      "desc": "Ask at the counter — today's bake changes daily.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "donut",
      "cat": "sweet",
      "name": "Iced Donut Ring",
      "price": 2,
      "desc": "Soft ring donut with a thick iced top.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "irnbru",
      "cat": "drinks",
      "name": "Irn Bru",
      "price": 1.5,
      "desc": "Scotland's other national drink. 330ml can.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "hot",
      "cat": "drinks",
      "name": "Tea / Coffee",
      "price": 1.8,
      "desc": "Freshly brewed, takeaway cup.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "juice",
      "cat": "drinks",
      "name": "Can of Juice",
      "price": 1.3,
      "desc": "Assorted soft drinks, 330ml.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    },
    {
      "id": "water",
      "cat": "drinks",
      "name": "Bottled Water",
      "price": 1.2,
      "desc": "Still, 500ml.",
      "badge": "",
      "badgeText": "",
      "home": false,
      "homeTag": "",
      "homeTagDark": true,
      "img": ""
    }
  ],
  "deals": {
    "featured": {
      "tag": "🔥 Deal of the Week",
      "title": "THE DONNER LUNCH DEAL",
      "desc": "The viral Big Daddy Donner pie + any sweet bake + a can of Irn Bru. The full Paisley experience for less than a fiver.",
      "was": "£7.80",
      "now": "£5.95",
      "unit": "Per Deal"
    },
    "list": [
      {
        "ribbon": "Best Value",
        "emoji": "🥧",
        "title": "PIE & A DRINK",
        "price": "£5.50",
        "was": "was £6.30",
        "desc": "Any signature or classic pie with a can of juice or hot drink. The quick lunch sorted.",
        "bullets": [
          "Any pie up to £4.80",
          "Any can or tea/coffee",
          "Collection or delivery"
        ],
        "ctaLabel": "Order This →",
        "ctaHref": "order.html"
      },
      {
        "ribbon": "Feeds 4",
        "emoji": "📦",
        "title": "FAMILY PIE BOX",
        "price": "£16.00",
        "was": "was £19.20",
        "desc": "Four pies of your choice, boxed up hot and ready to take home. Dinner done.",
        "bullets": [
          "Any 4 pies",
          "Mix & match flavours",
          "Save over £3"
        ],
        "ctaLabel": "Order This →",
        "ctaHref": "order.html"
      },
      {
        "ribbon": "Mornings",
        "emoji": "☕",
        "title": "BREKKIE ROLL & BREW",
        "price": "£3.50",
        "was": "was £4.00",
        "desc": "Any hot roll — sausage, black pudding or cheese & onion — with a fresh tea or coffee.",
        "bullets": [
          "Any hot roll",
          "Tea or coffee",
          "Before 11am, every day"
        ],
        "ctaLabel": "Order This →",
        "ctaHref": "order.html"
      },
      {
        "ribbon": "Match Day",
        "emoji": "⚽",
        "title": "SAINTS MATCH BUNDLE",
        "price": "£12.00",
        "was": "was £14.40",
        "desc": "Two pies, two sausage rolls and two Irn Brus. Black & white approved — perfect before kick-off at the SMISA.",
        "bullets": [
          "2 pies + 2 sausage rolls",
          "2 cans of Irn Bru",
          "On home-game weekends"
        ],
        "ctaLabel": "Order This →",
        "ctaHref": "order.html"
      },
      {
        "ribbon": "Sweet Tooth",
        "emoji": "🍰",
        "title": "BAKERS' HALF DOZEN",
        "price": "£11.00",
        "was": "was £13.20",
        "desc": "Any six sweet bakes — empire biscuits, tiffin, donuts and today's cake. Great for the office.",
        "bullets": [
          "Any 6 sweet bakes",
          "Mix & match",
          "Baked fresh that morning"
        ],
        "ctaLabel": "Order This →",
        "ctaHref": "order.html"
      },
      {
        "ribbon": "Students",
        "emoji": "🎓",
        "title": "STUDENT 10% OFF",
        "price": "10%",
        "was": "off everything",
        "desc": "Show a valid student ID in store and take 10% off your whole order. UWS and West College Scotland welcome.",
        "bullets": [
          "Valid student ID required",
          "In store only",
          "Not with other deals"
        ],
        "ctaLabel": "See The Menu →",
        "ctaHref": "menu.html"
      }
    ],
    "loyalty": {
      "cardTitle": "PIE CLUB CARD",
      "filled": 7,
      "total": 10,
      "heading": "BUY 9, GET THE 10TH FREE",
      "text": "Pick up a Pie Club card at the Causeyside Street counter. Every pie earns a stamp — fill the card and your tenth pie is on us. No app, no fuss, just more pie."
    },
    "finePrint": "Deals available at 25 Causeyside Street, Paisley. Meal deal prices apply to collection orders; delivery is subject to a £2.50 fee within 3 miles. Offers can't be combined unless stated and may change week to week. Match Day Bundle available on St Mirren FC home-game weekends only. Subject to availability — when it's sold out, it's sold out. This is a demo website; ordering does not place a real order."
  },
  "news": {
    "lead": {
      "tag": "🔥 Headline",
      "date": "May 2026",
      "title": "NEW FLAGSHIP OPENS ON CAUSEYSIDE STREET",
      "body": "After outgrowing the original Bridge Street unit, Paisley Pie Co. has moved its main shop to a bigger home at 25 Causeyside Street — more counter space, more pies on display, and now online ordering for collection and delivery.",
      "img": "storefront.jpg",
      "ctaLabel": "Order From The New Shop →",
      "ctaHref": "order.html"
    },
    "posts": [
      {
        "src": "Shop News",
        "date": "May 2026",
        "title": "ONLINE ORDERING IS LIVE",
        "body": "You can now build an order on the website and collect it hot from Causeyside Street — usually ready in 15 to 20 minutes. Delivery within 3 miles has also launched.",
        "by": "Paisley Pie Co."
      },
      {
        "src": "📺 BBC News",
        "date": "2024",
        "title": "THE PAISLEY PIE SHOP THAT WENT VIRAL",
        "body": "BBC News covered how a small Paisley pie shop racked up millions of views online with its Big Daddy Donner — and the queues that followed.",
        "by": "BBC News"
      },
      {
        "src": "🏛 Holyrood",
        "date": "2024",
        "title": "MOTION TABLED IN SCOTTISH PARLIAMENT",
        "body": "A motion was lodged at the Scottish Parliament congratulating Paisley Pie Co. on its success and contribution to the local Paisley economy.",
        "by": "Scottish Parliament"
      },
      {
        "src": "🏆 Award",
        "date": "2024",
        "title": "YOUNG BUSINESS PERSON OF THE YEAR",
        "body": "Founder Scott McGinlay was recognised as Young Business Person of the Year for building the brand from a single Paisley unit into a national supplier.",
        "by": "Local Business Awards"
      },
      {
        "src": "⚽ St Mirren",
        "date": "2025",
        "title": "PROUD SPONSORS OF THE SAINTS",
        "body": "Through Scott McGinlay Catering, the shop continues to sponsor and cater for St Mirren FC — backing the town's team in black and white.",
        "by": "Paisley Pie Co."
      },
      {
        "src": "🍽 Foodie Explorers",
        "date": "2024",
        "title": "\"A TARDIS OF PIES\"",
        "body": "Food bloggers Foodie Explorers praised the range packed into a small space — hot and cold pies, sausage rolls and sweet bakes worth the stop.",
        "by": "foodieexplorers.co.uk"
      },
      {
        "src": "🛒 Retail",
        "date": "2024",
        "title": "NOW STOCKED IN KEY STORE & NISA",
        "body": "Paisley Pie Co. pies are supplied to Key Stores and Nisa branches nationally, bringing the flavours beyond the Paisley shop counter.",
        "by": "Paisley Pie Co."
      },
      {
        "src": "🥧 Menu",
        "date": "Ongoing",
        "title": "CUSTOMER-NAMED PIES KEEP COMING",
        "body": "Ideas from the in-shop request book keep making the specials board — and when they do, the pie gets named after whoever suggested it.",
        "by": "Paisley Pie Co."
      }
    ]
  }
};

(function () {
  window.ppcData = function () {
    try { var draft = localStorage.getItem('ppc_admin_draft'); if (draft) return JSON.parse(draft); } catch (e) {}
    return window.PPC_DATA;
  };
  window.ppcMoney = function (n) { return '£' + Number(n).toFixed(2); };
})();
